name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -f SkyblockCore/pom.xml

      - name: Upload shaded JAR
        uses: actions/upload-artifact@v4
        with:
          name: SkyblockCore
          path: SkyblockCore/target/SkyblockCore-1.0-SNAPSHOT.jar
          if-no-files-found: error
